### PR TITLE
Norwegian localisation

### PR DESCRIPTION
**Pull request by Erlendms**
I hope I did it correctly! ☺️ 

- I changed the two instances of "en" to "no".
- And changed the strings - hopefully every string, and hopefully nothing that wasn't a string. 😛

### CODE REVIEW

**Comment by davidtaylorhq** [comment]
Thanks @Erlendms!

**Comment by Erlendms** [comment]
Cool!

If I rebuild my Discourse, should I then get with the localisation?

And does it take the language from my site? (I want to test it. 🙂 )

**Comment by davidtaylorhq** [comment]
Yup exactly - just update this plugin, and then assuming your site's default language is set to `no`, it should use these new strings

**Comment by Erlendms** [comment]
Oh, I saw now that the locale of the chat integration plugin has the more precise 'nb_NO' instead of just 'no'. 

Could you just change it to that? Or should I make a new PR?

(Edit: Norwegian has two variations of our written language. 🙃 "Bokmål" and "Nynorsk". So it's best to say either 'nb_NO' or 'nn_NO'. 🙂)

**Comment by davidtaylorhq** [comment]
Fixed in https://github.com/davidtaylorhq/discourse-telegram-notifications/commit/a6d9a476b6d9d1b32a03ad7c9bf069e14fbfb5d3

**Pull request merged**
